apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jgwijxn4o-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jgwijxn4o-dotnet-basic-gitops